// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOD5ygc1MGyF107AFGI689CUwY35DRLRI',
    appId: '1:786313869339:web:6bdba3e85dd6e27a14a0be',
    messagingSenderId: '786313869339',
    projectId: 'argumentor-208d9',
    authDomain: 'argumentor-208d9.firebaseapp.com',
    storageBucket: 'argumentor-208d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOD5ygc1MGyF107AFGI689CUwY35DRLRI',
    appId: '1:786313869339:android:6bdba3e85dd6e27a14a0be',
    messagingSenderId: '786313869339',
    projectId: 'argumentor-208d9',
    storageBucket: 'argumentor-208d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOD5ygc1MGyF107AFGI689CUwY35DRLRI',
    appId: '1:786313869339:ios:6bdba3e85dd6e27a14a0be',
    messagingSenderId: '786313869339',
    projectId: 'argumentor-208d9',
    storageBucket: 'argumentor-208d9.firebasestorage.app',
    iosClientId: '786313869339-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.argumentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOD5ygc1MGyF107AFGI689CUwY35DRLRI',
    appId: '1:786313869339:macos:6bdba3e85dd6e27a14a0be',
    messagingSenderId: '786313869339',
    projectId: 'argumentor-208d9',
    storageBucket: 'argumentor-208d9.firebasestorage.app',
    iosClientId: '786313869339-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.argumentor',
  );
}
